/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Recoverable,
  RecoverableInterface,
} from "../../../contracts/utils/Recoverable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "recoverFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Recoverable__factory {
  static readonly abi = _abi;
  static createInterface(): RecoverableInterface {
    return new utils.Interface(_abi) as RecoverableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Recoverable {
    return new Contract(address, _abi, signerOrProvider) as Recoverable;
  }
}
