/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as milkyWay from "./MilkyWay";
export type { milkyWay };
import type * as interface from "./interface";
export type { interface };
import type * as utils from "./utils";
export type { utils };
export type { Migrations } from "./Migrations";
export type { Multicall } from "./Multicall";
export type { PresaleService } from "./PresaleService";
export type { ReferralService } from "./ReferralService";
export type { SolarToken } from "./SolarToken";
export type { StakingService } from "./StakingService";
