/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as investController from "./InvestController";
export * as interface from "./interface";
export { BaseInvestController__factory } from "./BaseInvestController__factory";
export { InvestControl__factory } from "./InvestControl__factory";
export { MilkyWay__factory } from "./MilkyWay__factory";
