/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as investController from "./InvestController";
export type { investController };
import type * as interface from "./interface";
export type { interface };
export type { BaseInvestController } from "./BaseInvestController";
export type { InvestControl } from "./InvestControl";
export type { MilkyWay } from "./MilkyWay";
