/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as milkyWay from "./MilkyWay";
export * as interface from "./interface";
export * as utils from "./utils";
export { Migrations__factory } from "./Migrations__factory";
export { Multicall__factory } from "./Multicall__factory";
export { PresaleService__factory } from "./PresaleService__factory";
export { ReferralService__factory } from "./ReferralService__factory";
export { SolarToken__factory } from "./SolarToken__factory";
export { StakingService__factory } from "./StakingService__factory";
