/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interface from "./interface";
export { NmxInvestController__factory } from "./NmxInvestController__factory";
