/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBaseInvestController,
  IBaseInvestControllerInterface,
} from "../../../../contracts/MilkyWay/interface/IBaseInvestController";

const _abi = [
  {
    inputs: [],
    name: "claimAndBuyBack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_investingBnbAmount",
        type: "uint256",
      },
    ],
    name: "invest",
    outputs: [
      {
        internalType: "uint256",
        name: "investingAmount",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withdrawalAndRefoundToMilkyWal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBaseInvestController__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseInvestControllerInterface {
    return new utils.Interface(_abi) as IBaseInvestControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBaseInvestController {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IBaseInvestController;
  }
}
